### ISSUE TITLE
Homebridge crashes after installing plugin

### ISSUE THREAD

**Issue by piokaczo** [pkmnct/homebridge-lirc-tv#6]
Hi!

I am trying to install your plugin but after doing initial configuration and restarting server Homebridge crashes.

In logs there is:

[7/23/2020, 12:46:15 am] [ERROR]: uncaughtException: The requested platform 'LIRC' was not registered by any plugin.
Error: The requested platform 'LIRC' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by pkmnct** [comment]
@piokaczo It sounds like the plugin didn't install or initialize properly. Are there any other errors during the start of Homebridge?

**Comment by piokaczo** [comment]
This is the whole log. It loops crashes, tries again to run homebridge and the same is happening:

`[7/23/2020, 11:30:03 am] [INFO]: Homebridge Version: 2.4 
[7/23/2020, 11:30:03 am] [INFO]: SmartThings-v2 Plugin Version: 2.3.4 
[7/23/2020, 11:30:03 am] [INFO]: Checking Package Version for Updates... 
[7/23/2020, 11:30:04 am] [ERROR]: uncaughtException: The requested platform 'LIRC' was not registered by any plugin.
Error: The requested platform 'LIRC' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) 
`


When removing section in config.json right away everything is running fine:

`[7/23/2020, 11:31:10 am] [INFO]: Homebridge Version: 2.4 
[7/23/2020, 11:31:10 am] [INFO]: SmartThings-v2 Plugin Version: 2.3.4 
[7/23/2020, 11:31:10 am] [INFO]: Checking Package Version for Updates... 
[7/23/2020, 11:31:11 am] [INFO]: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded! 
[7/23/2020, 11:31:11 am] [GOOD]: Refreshing All Device Data | Source: (First Launch) 
[7/23/2020, 11:31:12 am] [NOTICE]: Temperature Unit is Now: (C) 
[7/23/2020, 11:31:12 am] [WARN]: Devices to Remove: (0) []
[7/23/2020, 11:31:12 am] [INFO]: Devices to Update: (2) 
[7/23/2020, 11:31:12 am] [GOOD]: Devices to Create: (0) []
[7/23/2020, 11:31:12 am] [ALERT]: Total Initialization Time: (1 seconds) 
[7/23/2020, 11:31:12 am] [NOTICE]: Unknown Capabilities: ["Ocf","Air Conditioner Mode","Air Conditioner Fan Mode","Fan Oscillation Mode","Air Quality Sensor","Odor Sensor","Dust Sensor","Very Fine Dust Sensor","Remote Control Status","Power Consumption Report","Demand Response Load Control","Execute","custom.spiMode","custom.thermostatSetpointControl","custom.airConditionerOptionalMode","custom.airConditionerTropicalNightMode","custom.autoCleaningMode","custom.deviceReportStateConfiguration","custom.energyType","custom.dustFilter","custom.veryFineDustFilter","custom.deodorFilter","custom.electricHepaFilter","custom.doNotDisturbMode","custom.periodicSensing","custom.airConditionerOdorController","custom.disabledCapabilities","samsungce.driverVersion"] 
[7/23/2020, 11:31:12 am] [INFO]: SmartThings DeviceCache Size: (2) 
[7/23/2020, 11:31:12 am] [INFO]: WebServer Initiated... 
[7/23/2020, 11:31:12 am] [INFO]: Sending StartDirect Request to SmartThings | SendToLocalHub: (false) 
[7/23/2020, 11:31:12 am] [INFO]: Direct Connect Active | Listening at 192.168.1.22:8000 
[7/23/2020, 11:31:19 am] [INFO]: INFO: Your plugin version is up-to-date 
[7/23/2020, 11:31:19 am] [NOTICE]: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.4 `

**Comment by pkmnct** [comment]
I'm not seeing any of the initialization text from the plugin, can you confirm that it appears in your global node_modules folder or Homebridge Config UI X Plugins page?

It should have output ```[LIRC] Initializing LIRC platform...``` in to your log shortly after starting Homebridge.

**Comment by piokaczo** [comment]
Yup. It is there.

> ls -l /usr/lib/node_modules/
> total 36
> drwxr-xr-x 5 root root 4096 lip 23 00:34 homebridge
> drwxr-xr-x 3 root root 4096 sty 17  2020 homebridge-airly2
> drwxr-xr-x 6 root root 4096 lip 23 00:37 homebridge-config-ui-x
> drwxr-xr-x 3 root root 4096 lip 24 09:25 homebridge-lirc
> drwxr-xr-x 4 root root 4096 lip 24 09:27 homebridge-lirc-tv
> drwxr-xr-x 4 root root 4096 sty 17  2020 homebridge-mi-airpurifier
> drwxr-xr-x 9 root root 4096 cze  7 18:46 homebridge-smartthings-v2
> drwxr-xr-x 6 root root 4096 sty 17  2020 miio
> drwxr-xr-x 9 root root 4096 lip 14 14:14 npm


> ls -l /usr/lib/node_modules/homebridge-lirc-tv/
> total 32
> -rw-r--r-- 1 root root  6012 paź 26  1985 config.schema.json
> drwxr-xr-x 2 root root  4096 lip 24 09:27 dist
> -rw-r--r-- 1 root root 10172 paź 26  1985 LICENSE
> -rw-r--r-- 1 root root  2107 lip 24 09:27 package.json
> -rw-r--r-- 1 root root   494 paź 26  1985 README.md

**Comment by pkmnct** [comment]
It looks like homebridge-lirc may be conflicting with homebridge-lirc-tv. Try disabling homebridge-lirc.

**Comment by piokaczo** [comment]
Unfortunately no. I've tried with and without homebridge-lirc - in both cases I got the same result :(

**Comment by pkmnct** [comment]
What version of Homebridge are you using? I see 2.4 in the log, but the [latest version is 1.1.1](https://www.npmjs.com/package/homebridge). What version of node and npm are you using, and what platform? Try removing the `homebridge-lirc-tv` folder from `/usr/lib/node_modules/` and re-installing (if you haven't already). The `Error: The requested platform 'LIRC' was not registered by any plugin` definitely suggests that the plugin is not being loaded by homebridge.

If nothing else I can also suggest trying [Homebridge Television Universal Control](https://github.com/pkmnct/homebridge-television-universal-control) instead. It supports LIRC as well.

**Comment by piokaczo** [comment]
Your comment gave me some idea. I've checked everything and it seems that I had some leftoevers of older version of homebridge and even that everything was running in newest 1.1.1 somehow while starting homebridge system detected the old one as running one. Anyway, now that I've done some maintenance everything is running great!

Thank you for your support!
